### ISSUE TITLE
NODE_PATH=    ????

### ISSUE THREAD

**Issue by almaweb** [ndabAP/vuex-cli-scaffold#2]
Hello,
Ihave this error....probaly i dont know what to use in NODE_PATH=

> yooteach@0.1.0 vuex-cli-scaffold C:\xampp\htdocs\new-project
> node ./node_modules/vuex-cli-scaffold/src/index.js "product"
> fs.js:922
  return binding.mkdir(pathModule._makeLong(path),
                 ^
> Error: ENOENT: no such file or directory, mkdir 'C:\xampp\htdocs\new-project\undefined\src\store\modules'

**Comment by ndabAP** [comment]
You have `undefined` in your path. Why is that?

Also try to run the command without `NODE_PATH=.`.
