### ISSUE TITLE
missing script: vuex-cli-scaffold

### ISSUE THREAD

**Issue by webmint** [ndabAP/vuex-cli-scaffold#4]
Fresh instalation on project with "node": "8.11.2",    "npm": "5.6.0"

**Comment by webmint** [comment]
Yes, sure

`{
  "name": "paybird-v2",
  "version": "1.0.0",
  "description": "New version of Paybird",
  "author": "webmint <webmintua@gmail.com>",
  "private": true,
  "scripts": {
    "dev": "webpack-dev-server --inline --progress --config build/webpack.dev.conf.js",
    "start": "node server.js",
    "lint": "eslint --ext .js,.vue src",
    "build": "node build/build.js"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "bootstrap-vue": "^2.0.0-rc.6",
    "element-ui": "^2.3.7",
    "express": "^4.16.3",
    "firebase": "^4.12.1",
    "firebaseui": "^2.7.0",
    "ipapi.co": "^0.2.3",
    "jwt-decode": "^2.2.0",
    "lodash.isempty": "^4.4.0",
    "moment": "^2.22.1",
    "paper-kit-2": "^2.1.0",
    "promise.prototype.finally": "^3.1.0",
    "vue": "^2.5.2",
    "vue-awesome": "^3.0.0",
    "vue-extend-layout": "^1.0.1",
    "vue-router": "^3.0.1",
    "vue-router-multiguard": "^1.0.3",
    "vue-the-mask": "^0.11.1",
    "vue2-scrollbar": "0.0.3",
    "vuelidate": "^0.6.2",
    "vuex": "^3.0.1",
    "vuex-map-fields": "^1.2.3",
    "vuex-persist": "^1.1.6"
  },
  "devDependencies": {
    "autoprefixer": "^7.1.2",
    "babel-core": "^6.22.1",
    "babel-eslint": "^8.2.1",
    "babel-helper-vue-jsx-merge-props": "^2.0.3",
    "babel-loader": "^7.1.1",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-plugin-transform-vue-jsx": "^3.5.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-2": "^6.22.0",
    "chalk": "^2.0.1",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.0",
    "eslint": "^4.15.0",
    "eslint-config-airbnb-base": "^11.3.0",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-import-resolver-webpack": "^0.8.3",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-vue": "^4.0.0",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^1.1.4",
    "friendly-errors-webpack-plugin": "^1.6.1",
    "html-webpack-plugin": "^2.30.1",
    "node-notifier": "^5.1.2",
    "node-sass": "^4.8.3",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "ora": "^1.2.0",
    "portfinder": "^1.0.13",
    "postcss-import": "^11.0.0",
    "postcss-loader": "^2.0.8",
    "postcss-url": "^7.2.1",
    "rimraf": "^2.6.0",
    "sass-loader": "^6.0.7",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "uglifyjs-webpack-plugin": "^1.1.1",
    "url-loader": "^0.5.8",
    "vue-loader": "^13.3.0",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "^2.5.2",
    "vuex-cli-scaffold": "^1.0.6",
    "webpack": "^3.6.0",
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-dev-server": "^2.9.1",
    "webpack-merge": "^4.1.0"
  },
  "engines": {
    "node": "8.11.2",
    "npm": "5.6.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}
`

**Comment by ndabAP** [comment]
Please try this:

`"vuex-cli-scaffold": "NODE_PATH=. node ./node_modules/vuex-cli-scaffold/src/index.js"`

**Comment by webmint** [comment]
working, Thank you!

maybe this should be added to documentation as well?

ps also worked this for me 

`"vuex-cli-scaffold": "node node_modules/vuex-cli-scaffold/src/index.js"`

**Comment by ndabAP** [comment]
You are absolutely right, this should be added to the documentation. I'll do that soon. Thanks for your feedback!
